services:
  gateway:
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/gateway/snippets:/etc/nginx/snippets:ro
      - ./docker/gateway/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/opt/certs:ro
    restart: always
    healthcheck:
      test: curl --fail http://127.0.0.1/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  site:
    build:
      context: .
      dockerfile: docker/site/Dockerfile
    depends_on:
      gateway:
        condition: service_healthy
    restart: always